In [7]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv("../data/tmdb_5000_movies.csv")
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [ ]:
# Keep required columns

df = df[['title', 'genres', 'overview']]
df.head()

,title,genres,overview
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca..."

In [11]:
#Handling missing value

df['overview'] = df['overview'].fillna('')
df['genres'] = df['genres'].fillna('')

In [14]:
# combine features of genres and overview

df['combined_features'] = df['genres'] +" " +df['overview']
df[['title', 'combined_features']].head()

,title,combined_features
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam..."
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."

In [16]:
#convert movie text into numeric value

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words = 'english')

tfidf_matrix = tfidf.fit_transform(df['combined_features'])

tfidf_matrix.shape

(4803, 20988)

In [17]:
# here each value will represent how similar two movies are

from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

cosine_sim.shape

(4803, 4803)

In [18]:
indices = pd.Series(df.index, index=df['title']).drop_duplicates()

def recommend_movies(movie_title, num_recommendations=5):
    if movie_title not in indices:
        return "Movie not found "
    
    idx = indices[movie_title]

    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:num_recommendations+1]

    movie_indices = [i[0] for i in sim_scores]

    return df['title'].iloc[movie_indices]

In [19]:
recommend_movies("Inception")

4401                   The Helix... Loaded
2897                                Cypher
134     Mission: Impossible - Rogue Nation
1271                              Pandorum
322                      The Fifth Element
Name: title, dtype: object

In [23]:
import requests

url = "https://api.themoviedb.org/3/search/movie"
params = {
    "api_key": "86251920f1b028301d9d794d2a199e1b",
    "query": "Interstellar"
}

r = requests.get(url, params=params)
print(r.status_code)
print(r.json())

200
{'page': 1, 'results': [{'adult': False, 'backdrop_path': '/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg', 'genre_ids': [12, 18, 878], 'id': 157336, 'original_language': 'en', 'original_title': 'Interstellar', 'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.', 'popularity': 41.7119, 'poster_path': '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 'release_date': '2014-11-05', 'title': 'Interstellar', 'video': False, 'vote_average': 8.467, 'vote_count': 38785}, {'adult': False, 'backdrop_path': '/wUZID3WzrzuIQmcIjXahZkV1ItI.jpg', 'genre_ids': [878], 'id': 398188, 'original_language': 'en', 'original_title': 'Interstellar Wars', 'overview': 'For millennia the Alien force has watched and waited, a brooding menace that has now at last decided to take over the Earth. Communications systems worldwide are sent into chaos by a strange atmospheric interference, a massive spaceship heads towards Earth and smaller spaceships begin to cover entire cities. Suddenly, the wonder turns into horror as the spaceships destroy the cities with energy weapons. When the world counterattacks, the alien ships are invincible to military weapons.  The survivors have to use their wits to kill the aliens, or die.', 'popularity': 0.2603, 'poster_path': '/4uWZ8cdrXMLiyLNgdmqQCIM6z40.jpg', 'release_date': '2016-06-09', 'title': 'Interstellar Wars', 'video': False, 'vote_average': 3.0, 'vote_count': 15}, {'adult': False, 'backdrop_path': None, 'genre_ids': [35], 'id': 287954, 'original_language': 'en', 'original_title': 'Lolita from Interstellar Space', 'overview': 'An undeniably beautiful alien is sent to Earth to study the complex mating rituals of human beings, which leads to the young interstellar traveler experiencing the passion that surrounds the centuries-old ritual of the species.', 'popularity': 0.6887, 'poster_path': '/nhWlip1s5YzhRFKGlHABGJrBhZn.jpg', 'release_date': '2014-03-08', 'title': 'Lolita from Interstellar Space', 'video': False, 'vote_average': 4.967, 'vote_count': 15}, {'adult': False, 'backdrop_path': None, 'genre_ids': [28], 'id': 649745, 'original_language': 'zh', 'original_title': '星际流浪', 'overview': 'The film tells that the catastrophe era, the earth is a waste land, the survivors are divided into wanderers and civilians, they are attached to the rule of the interstellar armed groups, in which the rogues rely on the plundering of civilian materials as a livelihood, making civilians in this harsh It is difficult to survive in the environment. After a hundred years of black technology explosion, it will bring about a civilized renaissance. In the face of the deteriorating planet, mankind is determined to continue the race and is determined to interstellar immigration. The "curvature engine" developed by the Chinese researcher Hailei has become the key to the interstellar immigration, and is also the target of robbers and interstellar armed groups.', 'popularity': 0.1338, 'poster_path': '/oUWDbde5bWu9syBZglWDIwB1SPm.jpg', 'release_date': '2019-08-02', 'title': 'Interstellar Wandering', 'video': False, 'vote_average': 2.0, 'vote_count': 1}, {'adult': False, 'backdrop_path': None, 'genre_ids': [28, 14, 878], 'id': 460616, 'original_language': 'en', 'original_title': 'Interstellar Civil War: Shadows of the Empire', 'overview': "The Imperial Empire is attacked by an Alliance of rebels led by fanatical mystics. The ruler, Empress Nobu, the 8th generation of her family, wants to execute a bold plan to rescue a cyborg, Leah C6, trapped on the battle ravaged planet Endor. The Empress believes Leah C6 holds the secret to destroying the Alliance of Rebels before their insurgency can kill millions of citizens of the Empire. She recruits her heroic fleet commander, Lord General Luka Raan and asks him to gather a team from the Empire's elite soldiers, the Galactic Rangers. Raan assembles the team in the ruins of Endor which was attacked by depraved Rebels and outlaws led by, Kindo-Ker, a fanatical mystic in Dark Energy. The Galactic Rangers begin a desperate search to find and rescue Leah C6 before the Alliance Rebels can.", 'popularity': 0.1749, 'poster_path': '/1lDY7ZpEKOl3OaIQURjRbmFPfT8.jpg', 'release_date': '2018-04-15', 'title': 'Interstellar Civil War: Shadows of the Empire', 'video': False, 'vote_average': 3.125, 'vote_count': 4}, {'adult': False, 'backdrop_path': '/z7JUwll8F1BSVc8NjVGelW87mcU.jpg', 'genre_ids': [99], 'id': 529107, 'original_language': 'en', 'original_title': "Inside 'Interstellar'", 'overview': 'Cast and crew of Christopher Nolan\'s "Interstellar" discuss project origins, the film\'s imagery, ambitions, incorporating IMAX footage, the human element within the film, arm shooting locations outside of Calgary, the set construction and design, working with real corn, mechanical characters, including backstory, design, the blend of practical and digital effects in bringing them to life, the differences in the characters, the human performances behind the characters, the creative process behind the film\'s music, Icelandic locations, vehicle interiors, the processes of simulating the absence of gravity, the crucial end-film visuals and influence and inspiration for future generations', 'popularity': 0.4752, 'poster_path': '/xWA7Bbo9VeahPcKCFYiC7NZXNoV.jpg', 'release_date': '2015-03-31', 'title': "Inside 'Interstellar'", 'video': False, 'vote_average': 6.9, 'vote_count': 10}, {'adult': False, 'backdrop_path': '/8C32MMrMYT5gON7nXgEGeM4puH4.jpg', 'genre_ids': [99], 'id': 336592, 'original_language': 'en', 'original_title': 'The Science of Interstellar', 'overview': "Matthew McConaughey narrates a fascinating look at Christopher Nolan's sci-fi film, 'Interstellar', including scientific foundations, the work of consulting Scientist Kip Thorne, basic film themes, the science behind the search for planets capable of hosting life, space-time and the theory of relativity, the science of wormholes and black holes, crafting the film's visuals based on real scientific observation, the birth of the universe, the Dust Bowl and the evolution of dust as a toxin, the likelihood of future dust storms, the prospects of escaping a dying or doomed planet and the possibilities of colonizing Mars.", 'popularity': 0.9452, 'poster_path': '/pUvbuOTHKQWrLuGY1x2pHd1evPL.jpg', 'release_date': '2014-11-13', 'title': 'The Science of Interstellar', 'video': False, 'vote_average': 6.9, 'vote_count': 35}, {'adult': False, 'backdrop_path': '/VMobpKawnYlOSTxBNqC1kCSGXB.jpg', 'genre_ids': [99, 10770], 'id': 301959, 'original_language': 'en', 'original_title': "Interstellar: Nolan's Odyssey", 'overview': "A look behind the lens of Christopher Nolan's space epic.", 'popularity': 0.5757, 'poster_path': '/i4PpBcuLvdcJwIf3hkcV9QDR1iH.jpg', 'release_date': '2014-11-05', 'title': "Interstellar: Nolan's Odyssey", 'video': False, 'vote_average': 7.7, 'vote_count': 184}, {'adult': False, 'backdrop_path': '/lQS9il7YqGjmmBefZY27uG5wbzT.jpg', 'genre_ids': [99], 'id': 660698, 'original_language': 'en', 'original_title': 'Faster Than Light: the Dream of Interstellar Flight', 'overview': '“Faster Than Light” explores the longstanding quest to develop spacecraft with enough power and speed to reach the stars. The film asks: What will it take to reach a newly discovered planet circling our Sun’s nearest neighbor, Proxima Centauri? Based on real science and engineering, “Faster Than Light” takes audiences on a thrilling journey into the future, aboard laser-driven space sails, antimatter engines, and even warp drive – right out of science fiction. “Who can say how far, and how fast, our technology will one day take us?” said director Thomas Lucas.', 'popularity': 0.3356, 'poster_path': '/mbgJxB70uMFK2H8DXHUj5lAMgXx.jpg', 'release_date': '2017-06-07', 'title': 'Faster Than Light: the Dream of Interstellar Flight', 'video': False, 'vote_average': 6.4, 'vote_count': 4}, {'adult': False, 'backdrop_path': None, 'genre_ids': [16, 878], 'id': 1391726, 'original_language': 'en', 'original_title': 'Interstellar Stella', 'overview': 'In a world formed by the spectacle of perfect illusions, the king of mediation travels through the lens to fight an anti-image cult that threatens a new generation.', 'popularity': 0.0404, 'poster_path': None, 'release_date': '2006-12-11', 'title': 'Interstellar Stella', 'video': False, 'vote_average': 0.0, 'vote_count': 0}, {'adult': False, 'backdrop_path': None, 'genre_ids': [], 'id': 986255, 'original_language': 'en', 'original_title': 'How to Colonize the Stars: The Challenge of Interstellar Flight', 'overview': "Leading physicists and engineers in the field of interstellar travel discuss some of the deep issues we face when considering the problem of sending spacecraft to other stars. Will mankind ever truly become a space fairing civilization? Space colonization is no longer the fodder of science fiction, it is becoming a reality. We'll need to learn how to grow food, manufacture and live off our planet.", 'popularity': 0.0357, 'poster_path': '/ddYoMPJioxY7qQxt7JyUaLCWMjw.jpg', 'release_date': '2009-06-09', 'title': 'How to Colonize the Stars: The Challenge of Interstellar Flight', 'video': False, 'vote_average': 10.0, 'vote_count': 1}, {'adult': False, 'backdrop_path': None, 'genre_ids': [53, 878], 'id': 1282990, 'original_language': 'en', 'original_title': 'Interstellar Interference', 'overview': "During a calm lil hang at Mike's crib, the boys finds themselves facing an unimaginable terror when an otherworldly intruder breaches their sanctuary. As the night unfolds, paranoia grips the group as they realize the sinister intentions of their unwelcome guest. With each passing moment, the line between survival and demise blurs, forcing them to confront their deepest fears and fight for their lives against an entity that knows no mercy. In this heart-pounding thriller, every shadow holds a deadly secret, and every corner hides a chilling revelation as the battle for survival unfolds in the most unexpected of places.", 'popularity': 0.0286, 'poster_path': '/2yHZyjf9DC2y2wsOckiTmn7ZJLp.jpg', 'release_date': '2023-04-22', 'title': 'Interstellar Interference', 'video': False, 'vote_average': 0.0, 'vote_count': 0}, {'adult': False, 'backdrop_path': None, 'genre_ids': [12], 'id': 552531, 'original_language': 'en', 'original_title': "The Prom Goer's Interstellar Excursion", 'overview': 'High schooler Bennett lands the prom date of his dreams, Sophie, just days before the dance. Not long after, he witnesses Sophie being abducted by aliens in the middle of the New Mexico desert.', 'popularity': 0.0214, 'poster_path': None, 'release_date': '', 'title': "The Prom Goer's Interstellar Excursion", 'video': False, 'vote_average': 0.0, 'vote_count': 0}, {'adult': False, 'backdrop_path': None, 'genre_ids': [35, 18], 'id': 716603, 'original_language': 'en', 'original_title': 'Only Interstellar Pinball Lives Forever', 'overview': "A young boy (played by an actual re-purposed Sunday school puppet) loses all faith in religion and afterlife options after having to bury his umpteenth pet, and vows that someday, when he's an adult with money, he'll find a way to become an 'eternal molecule' through science. Then, twenty-two years later, the playing of a pinball game brings dredges up the memory of that vow. Utilizing the hallucinogenic properties of alcohol and cough syrup blends, he undertakes the design of a pinball machine so poignant and dignified that it will convince scientists to create a pinball that we can download our consciousness into and thereby become digitally immortal.", 'popularity': 0.0143, 'poster_path': '/uLJMGZlrkmvAO9Ria9zrp8GUqjx.jpg', 'release_date': '2010-06-28', 'title': 'Only Interstellar Pinball Lives Forever', 'video': False, 'vote_average': 7.0, 'vote_count': 1}, {'adult': False, 'backdrop_path': None, 'genre_ids': [], 'id': 1501040, 'original_language': 'en', 'original_title': 'The Future is Now: A Look Back at Interstellar', 'overview': 'A brief (23 minutes) retrospective on the film, but what it lacks in length it makes up for with insight. Featuring input from key collaborators like producer Emma Thomas, co-writer Jonathan Nolan, cinematographer Hoyle van Hoytema, co-producer Kip Thorne, and Interstellar admirers like Denis Villnevue, Peter Jackson, critic Kenneth Turan, Josh Hartnett, this is a mostly standard look back, but if you’re in this movie’s choir you’ll enjoy the preaching.', 'popularity': 0.0193, 'poster_path': None, 'release_date': '2024-12-10', 'title': 'The Future is Now: A Look Back at Interstellar', 'video': True, 'vote_average': 0.0, 'vote_count': 0}, {'adult': False, 'backdrop_path': None, 'genre_ids': [99], 'id': 763179, 'original_language': 'en', 'original_title': 'Cosmic Journey: The Voyager Interstellar Mission and Message', 'overview': 'The farthest Voyager: "Cosmic Journey," a documentary premiering on the A&E cable network, tells the saga of the farthest-flung space journey to date - the Voyager interstellar mission, which started out 25 years ago and sailed past Jupiter, Saturn, Uranus and Neptune in the 1980s.', 'popularity': 0.0071, 'poster_path': None, 'release_date': '2003-01-16', 'title': 'Cosmic Journey: The Voyager Interstellar Mission and Message', 'video': False, 'vote_average': 2.5, 'vote_count': 1}, {'adult': False, 'backdrop_path': None, 'genre_ids': [99, 36], 'id': 1573960, 'original_language': 'en', 'original_title': 'Shouting at Stars: A History of Interstellar Messages', 'overview': 'Since the early 1970s, humanity has sent messages beyond the Solar System in the hopes of contacting another civilization. Some were physically attached to interstellar spacecraft, while others were beamed into space in the form of radio signals. This documentary provides a detailed chronology of almost all of these messages with a focus on their meaning and improbability of reception', 'popularity': 0.0143, 'poster_path': '/hrRuQbG7UE0LD3EktofTR5N7QPM.jpg', 'release_date': '2025-10-31', 'title': 'Shouting at Stars: A History of Interstellar Messages', 'video': False, 'vote_average': 0.0, 'vote_count': 0}, {'adult': False, 'backdrop_path': None, 'genre_ids': [878, 16], 'id': 1443305, 'original_language': 'de', 'original_title': 'Container Interstellar', 'overview': 'Director Helmut Herbst’s animated sci-fi short with characters that would be more fully explored in CATHEDRAL OF NEW EMOTIONS.', 'popularity': 0.0264, 'poster_path': '/dp7ch6CGdNnNpcidyzBaFabmEJW.jpg', 'release_date': '2001-01-01', 'title': 'Container Interstellar', 'video': False, 'vote_average': 7.5, 'vote_count': 2}, {'adult': False, 'backdrop_path': None, 'genre_ids': [], 'id': 1450827, 'original_language': 'en', 'original_title': 'Interstellar Political Prisoner', 'overview': 'I am Kepler, an exile from the planet Guarding. A long time ago, I asked myself a question: "What am I?" Since then, I began a long search for the meaning of my existence. When I finally got the answer, the day of exile was approaching...', 'popularity': 0.0, 'poster_path': '/1A0wLpRmpMLaoDRGhzvctyeoogp.jpg', 'release_date': '2016-09-25', 'title': 'Interstellar Political Prisoner', 'video': False, 'vote_average': 0.0, 'vote_count': 0}, {'adult': False, 'backdrop_path': None, 'genre_ids': [], 'id': 1601741, 'original_language': 'en', 'original_title': 'Doctor Who: The Interstellar Song Contest', 'overview': "The Doctor's mission to return Belinda to Earth brings them to a space station's song competition. What starts as entertainment turns into a fight for survival.  Artwork done by paulburleyffs", 'popularity': 0.0297, 'poster_path': '/1t7PKjC3hqZ2k9NkrYLiJV2wizF.jpg', 'release_date': '2025-05-17', 'title': 'Doctor Who: The Interstellar Song Contest', 'video': False, 'vote_average': 0.0, 'vote_count': 0}], 'total_pages': 2, 'total_results': 27}